ERROR - 2024-07-27 09:06:19 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\xampp\htdocs\benoite\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\xampp\htdocs\benoite\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\benoite\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\benoite\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\xampp\htdocs\benoite\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\xampp\htdocs\benoite\app\Controllers\Auth.php(26): CodeIgniter\BaseModel->save(Array)
#9 D:\xampp\htdocs\benoite\system\CodeIgniter.php(933): App\Controllers\Auth->store()
#10 D:\xampp\htdocs\benoite\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\xampp\htdocs\benoite\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\benoite\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\benoite\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\benoite\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\benoite\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
ERROR - 2024-07-27 09:06:29 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\xampp\htdocs\benoite\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\xampp\htdocs\benoite\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\benoite\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\benoite\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\xampp\htdocs\benoite\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\xampp\htdocs\benoite\app\Controllers\Auth.php(26): CodeIgniter\BaseModel->save(Array)
#9 D:\xampp\htdocs\benoite\system\CodeIgniter.php(933): App\Controllers\Auth->store()
#10 D:\xampp\htdocs\benoite\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\xampp\htdocs\benoite\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\benoite\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\benoite\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\benoite\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\benoite\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
ERROR - 2024-07-27 09:06:51 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\xampp\htdocs\benoite\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\xampp\htdocs\benoite\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\benoite\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\benoite\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\xampp\htdocs\benoite\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\xampp\htdocs\benoite\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->save(Array)
#9 D:\xampp\htdocs\benoite\system\CodeIgniter.php(933): App\Controllers\Auth->store()
#10 D:\xampp\htdocs\benoite\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\xampp\htdocs\benoite\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\benoite\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\benoite\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\benoite\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\benoite\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2024-07-27 10:09:43 --> ParseError: syntax error, unexpected variable "$password", expecting "function" or "const"
[Method: GET, Route: login]
in APPPATH\Controllers\Auth.php on line 83.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs\\benoite\\app\\Controllers\\Auth.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Auth')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Auth')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\Auth', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\benoite\\public\\index.php')
